"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { adminFetch } from "@/lib/admin/client";

type Report=any;
const fmt=(ms:number)=>ms<60000?`${Math.round(ms/1000)}s`:`${Math.floor(ms/60000)}m ${Math.round(ms%60000/1000)}s`;
export default function AnalyticsPage(){const ar=useSearchParams().get('lang')==='ar';const [days,setDays]=useState(30);const [report,setReport]=useState<Report>(null);const [status,setStatus]=useState('');
async function load(){setStatus(ar?'جاري التحميل...':'Loading...');const r=await adminFetch(`/api/admin/analytics?days=${days}`);if(r.ok){setReport((await r.json()).report);setStatus('')}else setStatus(ar?'فشل التحميل':'Load failed')};useEffect(()=>{load()},[days]);
const labels=ar?{empty:'لا توجد بيانات بعد. فعّل التحليلات الداخلية من صفحة Pixels، احفظ، ثم افتح الموقع العام وتصفحه قبل العودة هنا.',title:'تحليلات الزوار',desc:'اعرف الصفحات التي زاروها، ما قاموا به، مدة التفاعل، وآخر صفحة قبل المغادرة.',vis:'الزوار',ses:'الجلسات',pv:'مشاهدات الصفحات',avg:'متوسط التفاعل',conv:'التحويلات',top:'أكثر الصفحات زيارة',exit:'صفحات الخروج المحتملة',events:'الأنشطة',journey:'آخر مسارات الزوار',entry:'الدخول',last:'الخروج',duration:'المدة'}:{empty:'No activity has been recorded yet. Enable first-party analytics on the Pixels page, save it, then browse the public website before returning here.',title:'Visitor Analytics',desc:'See pages visited, activities, engagement time, journeys, and the likely last page before visitors left.',vis:'Visitors',ses:'Sessions',pv:'Page views',avg:'Avg. engagement',conv:'Conversions',top:'Top pages',exit:'Likely exit pages',events:'Activities',journey:'Recent visitor journeys',entry:'Entry',last:'Exit',duration:'Duration'};
return <div className="mx-auto max-w-6xl space-y-6" dir={ar?'rtl':'ltr'}><section className="rounded-3xl bg-white p-8 shadow-sm"><div className="flex flex-wrap justify-between gap-5"><div><h1 className="text-3xl font-black">{labels.title}</h1><p className="mt-3 text-slate-500">{labels.desc}</p></div><select value={days} onChange={e=>setDays(Number(e.target.value))} className="rounded-2xl border px-4 py-3"><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></div>{status&&<p>{status}</p>}</section>
{report&&report.summary.sessions===0&&<section className="rounded-3xl border border-amber-200 bg-amber-50 p-6 text-amber-950"><strong>{labels.empty}</strong></section>}
{report&&<><div className="grid gap-4 md:grid-cols-5">{[[labels.vis,report.summary.visitors],[labels.ses,report.summary.sessions],[labels.pv,report.summary.pageViews],[labels.avg,fmt(report.summary.averageEngagementMs)],[labels.conv,report.summary.conversions]].map(([l,v])=><div key={String(l)} className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-sm font-bold text-slate-500">{l}</p><strong className="mt-2 block text-3xl">{v}</strong></div>)}</div>
<div className="grid gap-5 lg:grid-cols-3">{[[labels.top,report.topPages],[labels.exit,report.exitPages],[labels.events,report.events]].map(([title,items]:any)=><section key={title} className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">{title}</h2><div className="mt-5 grid gap-3">{items.map((x:any)=><div key={x.name} className="flex justify-between gap-3 border-b border-slate-100 pb-3"><span className="truncate">{x.name}</span><strong>{x.value}</strong></div>)}</div></section>)}</div>
<section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">{labels.journey}</h2><div className="mt-5 grid gap-4">{report.recentSessions.map((s:any)=><article key={s.sessionId} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-3"><strong>{labels.entry}: {s.entryPage}</strong><span>{labels.duration}: {fmt(s.durationMs)}</span></div><p className="mt-2 text-sm text-slate-500">{s.path.join(' → ') || s.entryPage}</p><p className="mt-2 text-sm font-bold">{labels.last}: {s.exitPage}</p></article>)}</div></section></>}
</div>}
