"use client";

import { useEffect, useMemo, useState } from "react";
import { adminFetch } from "@/lib/admin/client";
import type { SiteTheme } from "@/lib/theme/site-theme";

const defaultTheme: SiteTheme = {
  name:"Qyasat Elegant Light", mode:"light",
  colors:{background:"#f7f4ef",surface:"#ffffff",surfaceMuted:"#f0ebe3",text:"#151515",muted:"#6f6a63",primary:"#111111",primaryText:"#ffffff",border:"#ded7cb",accent:"#b68b3c"},
  footer:{heading:"#ffffff",text:"rgba(255, 255, 255, 0.82)",muted:"rgba(255, 255, 255, 0.58)",accent:"#25f4ff",border:"rgba(255, 255, 255, 0.12)"},
  typography:{arabicFont:'"IBM Plex Sans Arabic"',englishFont:'"Inter"',headingFont:'"IBM Plex Sans Arabic"',baseSize:"16px",headingWeight:"900",letterSpacing:"-0.03em"},
  radius:{card:"28px",button:"999px"}, layout:{maxWidth:"1160px",density:"comfortable"}, effects:{heroGlow:"rgba(182, 139, 60, 0.20)",glass:true}
};
const arabicFonts=['"IBM Plex Sans Arabic"','"Tajawal"','"Cairo"','"Almarai"','"Noto Kufi Arabic"','"Noto Sans Arabic"'];
const englishFonts=['"Inter"','"Geist"','"Manrope"','"Montserrat"','"Poppins"','"Roboto"'];
const presets=[
  {label:"Luxury Light",theme:defaultTheme},
  {label:"Black Gold",theme:{...defaultTheme,name:"Black Gold",mode:"dark" as const,colors:{background:"#0f0f0f",surface:"#171717",surfaceMuted:"#222222",text:"#ffffff",muted:"#a3a3a3",primary:"#d4af37",primaryText:"#111111",border:"#2f2f2f",accent:"#d4af37"},footer:{heading:"#ffffff",text:"rgba(255, 255, 255, 0.86)",muted:"rgba(255, 255, 255, 0.60)",accent:"#d4af37",border:"rgba(212, 175, 55, 0.25)"},typography:{...defaultTheme.typography,arabicFont:'"Tajawal"',englishFont:'"Montserrat"',headingFont:'"Tajawal"'},effects:{heroGlow:"rgba(212, 175, 55, 0.22)",glass:true}}},
  {label:"Tech Blue",theme:{...defaultTheme,name:"Tech Blue",mode:"soft" as const,colors:{background:"#eef5ff",surface:"#ffffff",surfaceMuted:"#dbeafe",text:"#0f172a",muted:"#475569",primary:"#2563eb",primaryText:"#ffffff",border:"#bfdbfe",accent:"#0ea5e9"},footer:{heading:"#ffffff",text:"rgba(255, 255, 255, 0.86)",muted:"rgba(255, 255, 255, 0.62)",accent:"#38bdf8",border:"rgba(56, 189, 248, 0.25)"},typography:{...defaultTheme.typography,arabicFont:'"Cairo"',headingFont:'"Cairo"',headingWeight:"800"},effects:{heroGlow:"rgba(37, 99, 235, 0.18)",glass:true}}}
];

function nested<K extends keyof SiteTheme>(theme:SiteTheme,section:K,key:keyof SiteTheme[K],value:string|boolean){return {...theme,[section]:{...(theme[section] as object),[key]:value}};}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid min-w-0 gap-2"><span className="text-sm font-bold text-slate-500">{label}</span>{children}</label>}
const input="min-w-0 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100";

export default function ThemeAdminPage(){
 const [theme,setTheme]=useState<SiteTheme>(defaultTheme); const [saved,setSaved]=useState<SiteTheme>(defaultTheme);
 const [status,setStatus]=useState("Loading theme…"); const [busy,setBusy]=useState(false);
 const dirty=useMemo(()=>JSON.stringify(theme)!==JSON.stringify(saved),[theme,saved]);
 async function load(){setBusy(true);setStatus("Loading theme…");try{const r=await adminFetch("/api/admin/theme");const d=await r.json();if(!r.ok)throw new Error(d.error||"Load failed");setTheme(d.theme);setSaved(d.theme);setStatus("Theme loaded.");}catch(e){setStatus(e instanceof Error?e.message:"Load failed");}finally{setBusy(false)}}
 async function save(){setBusy(true);setStatus("Saving theme…");try{const r=await adminFetch("/api/admin/theme",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(theme)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Save failed");setTheme(d.theme);setSaved(d.theme);setStatus("Saved. Refresh the public website to see the theme.");}catch(e){setStatus(e instanceof Error?e.message:"Save failed");}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 const colorEntries=Object.entries(theme.colors) as [keyof SiteTheme["colors"],string][];
 const footerColorEntries=Object.entries(theme.footer) as [keyof SiteTheme["footer"],string][];
 return <div className="mx-auto max-w-6xl space-y-6 pb-16">
  <section className="rounded-3xl bg-white p-6 shadow-sm md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-black">Theme & Style</h1><p className="mt-2 text-slate-500">Changes are saved centrally and applied to the Arabic and English public website.</p></div><div className="flex flex-wrap gap-3"><button disabled={busy} onClick={load} className="rounded-2xl bg-slate-950 px-5 py-3 font-bold text-white disabled:opacity-50">Reload</button><button disabled={busy||!dirty} onClick={()=>setTheme(saved)} className="rounded-2xl border border-slate-200 px-5 py-3 font-bold disabled:opacity-40">Discard</button><button disabled={busy||!dirty} onClick={save} className="rounded-2xl bg-emerald-600 px-5 py-3 font-bold text-white disabled:opacity-40">Save Theme</button></div></div><p className={`mt-4 text-sm font-bold ${dirty?"text-amber-600":"text-slate-500"}`}>{dirty?"Unsaved changes — preview is live below.":status}</p></section>

  <section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Presets</h2><div className="mt-4 flex flex-wrap gap-3">{presets.map(p=><button key={p.label} onClick={()=>setTheme(structuredClone(p.theme))} className="rounded-2xl border border-slate-200 px-5 py-3 font-bold hover:bg-slate-50">{p.label}</button>)}</div></section>

  <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]">
   <section className="min-w-0 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Colors</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{colorEntries.map(([key,value])=><Field key={key} label={key}><div className="grid min-w-0 grid-cols-[48px_minmax(0,1fr)] gap-2"><input aria-label={`${key} picker`} type="color" value={value.startsWith("#")?value:"#000000"} onChange={e=>setTheme(nested(theme,"colors",key,e.target.value))} className="h-12 w-12 cursor-pointer rounded-xl border border-slate-200 p-1"/><input value={value} onChange={e=>setTheme(nested(theme,"colors",key,e.target.value))} className={input}/></div></Field>)}</div></section>
   <section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">General Style</h2><div className="mt-5 grid gap-4"><Field label="Theme Name"><input className={input} value={theme.name} onChange={e=>setTheme({...theme,name:e.target.value})}/></Field><Field label="Mode"><select className={input} value={theme.mode} onChange={e=>setTheme({...theme,mode:e.target.value as SiteTheme["mode"]})}><option value="light">Light</option><option value="dark">Dark</option><option value="soft">Soft</option></select></Field><Field label="Card Radius"><input className={input} value={theme.radius.card} onChange={e=>setTheme(nested(theme,"radius","card",e.target.value))}/></Field><Field label="Button Radius"><input className={input} value={theme.radius.button} onChange={e=>setTheme(nested(theme,"radius","button",e.target.value))}/></Field><Field label="Maximum Content Width"><input className={input} value={theme.layout.maxWidth} onChange={e=>setTheme(nested(theme,"layout","maxWidth",e.target.value))}/></Field><Field label="Layout Density"><select className={input} value={theme.layout.density} onChange={e=>setTheme(nested(theme,"layout","density",e.target.value))}><option value="compact">Compact</option><option value="comfortable">Comfortable</option><option value="spacious">Spacious</option></select></Field><Field label="Hero Glow"><input className={input} value={theme.effects.heroGlow} onChange={e=>setTheme(nested(theme,"effects","heroGlow",e.target.value))}/></Field><label className="flex items-center justify-between rounded-2xl border border-slate-200 p-4"><span className="font-bold">Glass effect</span><input type="checkbox" checked={theme.effects.glass} onChange={e=>setTheme(nested(theme,"effects","glass",e.target.checked))} className="h-5 w-5"/></label></div></section>
  </div>


  <section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-col gap-2"><h2 className="text-xl font-black">Footer Text Colors</h2><p className="text-sm text-slate-500">Control footer headings, normal text, muted text, links/highlights, and divider color independently from the page theme.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{footerColorEntries.map(([key,value])=><Field key={key} label={`Footer ${key}`}><div className="grid min-w-0 grid-cols-[48px_minmax(0,1fr)] gap-2"><input aria-label={`footer ${key} picker`} type="color" value={value.startsWith("#")?value:"#ffffff"} onChange={e=>setTheme(nested(theme,"footer",key,e.target.value))} className="h-12 w-12 cursor-pointer rounded-xl border border-slate-200 p-1"/><input value={value} onChange={e=>setTheme(nested(theme,"footer",key,e.target.value))} className={input}/></div></Field>)}</div><div className="mt-6 rounded-3xl p-6" style={{background:"linear-gradient(135deg,#07111c,#0b1725 52%,#09101a)",border:`1px solid ${theme.footer.border}`}}><div className="grid gap-4 md:grid-cols-3"><div><h3 className="text-lg font-black" style={{color:theme.footer.heading}}>Qyasat</h3><p className="mt-2" style={{color:theme.footer.text}}>Footer body text preview.</p><small style={{color:theme.footer.muted}}>Muted footer text preview.</small></div><div><h3 className="font-black" style={{color:theme.footer.heading}}>Quick Links</h3><a className="mt-2 block" style={{color:theme.footer.text}}>Services</a><a className="mt-2 block" style={{color:theme.footer.accent}}>Highlighted link</a></div><div className="border-t pt-4 md:border-l md:border-t-0 md:pl-4" style={{borderColor:theme.footer.border}}><strong style={{color:theme.footer.accent}}>EMAIL</strong><p style={{color:theme.footer.text}}>hello@qyasat.sa</p></div></div></div></section>
  <section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Typography</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="Arabic Font"><select className={input} value={theme.typography.arabicFont} onChange={e=>setTheme(nested(theme,"typography","arabicFont",e.target.value))}>{arabicFonts.map(f=><option key={f} value={f}>{f.replaceAll('"','')}</option>)}</select></Field><Field label="English Font"><select className={input} value={theme.typography.englishFont} onChange={e=>setTheme(nested(theme,"typography","englishFont",e.target.value))}>{englishFonts.map(f=><option key={f} value={f}>{f.replaceAll('"','')}</option>)}</select></Field><Field label="Heading Font"><select className={input} value={theme.typography.headingFont} onChange={e=>setTheme(nested(theme,"typography","headingFont",e.target.value))}>{[...arabicFonts,...englishFonts].map(f=><option key={f} value={f}>{f.replaceAll('"','')}</option>)}</select></Field><Field label="Base Font Size"><input className={input} value={theme.typography.baseSize} onChange={e=>setTheme(nested(theme,"typography","baseSize",e.target.value))}/></Field><Field label="Heading Weight"><select className={input} value={theme.typography.headingWeight} onChange={e=>setTheme(nested(theme,"typography","headingWeight",e.target.value))}>{[600,700,800,900].map(w=><option key={w}>{w}</option>)}</select></Field><Field label="Letter Spacing"><input className={input} value={theme.typography.letterSpacing} onChange={e=>setTheme(nested(theme,"typography","letterSpacing",e.target.value))}/></Field></div></section>

  <section className="overflow-hidden rounded-3xl border p-8 shadow-sm" style={{background:theme.colors.background,color:theme.colors.text,borderColor:theme.colors.border,fontFamily:theme.typography.englishFont}}><div className="mx-auto" style={{maxWidth:theme.layout.maxWidth}}><p className="text-sm font-bold" style={{color:theme.colors.muted}}>Live preview</p><div className="mt-5 grid gap-5 md:grid-cols-2"><div className="p-7" style={{background:theme.effects.glass?`color-mix(in srgb, ${theme.colors.surface} 82%, transparent)`:theme.colors.surface,border:`1px solid ${theme.colors.border}`,borderRadius:theme.radius.card,boxShadow:`0 20px 70px ${theme.effects.heroGlow}`}}><h2 className="text-4xl" style={{fontFamily:theme.typography.headingFont,fontWeight:theme.typography.headingWeight,letterSpacing:theme.typography.letterSpacing}}>Qyasat Theme</h2><p className="mt-3" style={{color:theme.colors.muted,fontSize:theme.typography.baseSize}}>This preview updates immediately. Save to apply it to the live Arabic and English pages.</p><div className="mt-6 flex flex-wrap gap-3"><button className="px-6 py-3 font-black" style={{background:theme.colors.primary,color:theme.colors.primaryText,borderRadius:theme.radius.button}}>Primary Button</button><button className="px-6 py-3 font-black" style={{color:theme.colors.text,border:`1px solid ${theme.colors.border}`,borderRadius:theme.radius.button}}>Secondary</button></div></div><div className="grid gap-3 p-5" style={{background:theme.colors.surfaceMuted,borderRadius:theme.radius.card}}>{["Surface","Muted surface","Accent"].map((x,i)=><div key={x} className="rounded-2xl p-4" style={{background:i===1?theme.colors.surfaceMuted:theme.colors.surface,border:`1px solid ${theme.colors.border}`}}><strong style={{color:i===2?theme.colors.accent:theme.colors.text}}>{x}</strong><p className="mt-1 text-sm" style={{color:theme.colors.muted}}>Reusable website component preview.</p></div>)}</div></div></div></section>
 </div>
}
