"use client";

import { useCallback, useEffect, useState, type ReactNode } from "react";
import { adminFetch } from "@/lib/admin/client";
import type { ProjectAccent, ProjectItem, ProjectOutcome, ProjectsContent } from "@/lib/projects-content";

type Locale = "ar" | "en";

const empty: ProjectsContent = {
  eyebrow:"",titleA:"",titleB:"",intro:"",primary:"",secondary:"",digitalKicker:"",digitalTitle:"",digitalText:"",opsKicker:"",opsTitle:"",opsText:"",outcomeKicker:"",outcomeTitle:"",outcomes:[],ctaTitle:"",ctaText:"",cta:"",cmsLabel:"",liveLabel:"",workflowLabel:"",digitalProjects:[],operatingProjects:[]
};

const input = "rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-900 outline-none focus:border-teal-700 focus:ring-4 focus:ring-teal-700/10";

function Field({ label, value, onChange, multiline=false, dir="ltr" }: { label:string; value:string; onChange:(v:string)=>void; multiline?:boolean; dir?:"rtl"|"ltr" }) {
  return <label className="grid gap-2"><span className="text-xs font-black text-slate-500">{label}</span>{multiline?<textarea dir={dir} className={`${input} min-h-28 leading-7`} value={value} onChange={e=>onChange(e.target.value)}/>:<input dir={dir} className={input} value={value} onChange={e=>onChange(e.target.value)}/>}</label>;
}
function Panel({ title, eyebrow, children }: { title:string; eyebrow:string; children:ReactNode }) {
  return <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 border-b border-slate-100 pb-5"><p className="text-xs font-black uppercase tracking-wider text-teal-700">{eyebrow}</p><h2 className="mt-2 text-2xl font-black">{title}</h2></div>{children}</section>;
}
function ProjectEditor({ title, items, onChange, dir }: { title:string; items:ProjectItem[]; onChange:(v:ProjectItem[])=>void; dir:"rtl"|"ltr" }) {
  const update=(i:number, patch:Partial<ProjectItem>)=>onChange(items.map((x,n)=>n===i?{...x,...patch}:x));
  return <div className="grid gap-4"><div className="flex items-center justify-between"><h3 className="text-lg font-black">{title}</h3><button className="rounded-2xl bg-slate-950 px-4 py-3 text-sm font-black text-white" onClick={()=>onChange([...items,{name:"",category:"",description:"",features:[],accent:"primary"}])}>Add project</button></div>{items.map((item,i)=><article key={i} className="rounded-3xl border border-slate-200 bg-slate-50 p-4"><div className="mb-4 flex items-center justify-between"><strong>Project {i+1}</strong><button className="rounded-xl bg-red-50 px-3 py-2 text-xs font-black text-red-700" onClick={()=>onChange(items.filter((_,n)=>n!==i))}>Remove</button></div><div className="grid gap-4 xl:grid-cols-2"><Field label="Project name" value={item.name} dir={dir} onChange={v=>update(i,{name:v})}/><Field label="Category" value={item.category} dir={dir} onChange={v=>update(i,{category:v})}/><div className="xl:col-span-2"><Field label="Description" value={item.description} dir={dir} multiline onChange={v=>update(i,{description:v})}/></div><Field label="Features (comma separated)" value={item.features.join(", ")} dir={dir} onChange={v=>update(i,{features:v.split(",").map(x=>x.trim()).filter(Boolean)})}/><label className="grid gap-2"><span className="text-xs font-black text-slate-500">Accent</span><select className={input} value={item.accent} onChange={e=>update(i,{accent:e.target.value as ProjectAccent})}><option value="primary">Primary theme color</option><option value="accent">Accent theme color</option><option value="neutral">Neutral</option></select></label></div></article>)}</div>;
}
function OutcomeEditor({ items, onChange, dir }: { items:ProjectOutcome[]; onChange:(v:ProjectOutcome[])=>void; dir:"rtl"|"ltr" }) {
  const update=(i:number, patch:Partial<ProjectOutcome>)=>onChange(items.map((x,n)=>n===i?{...x,...patch}:x));
  return <div className="grid gap-4"><div className="flex items-center justify-between"><h3 className="text-lg font-black">Outcome cards</h3><button className="rounded-2xl bg-slate-950 px-4 py-3 text-sm font-black text-white" onClick={()=>onChange([...items,{number:String(items.length+1).padStart(2,"0"),title:"",text:""}])}>Add outcome</button></div>{items.map((item,i)=><div key={i} className="grid gap-3 rounded-3xl border border-slate-200 bg-slate-50 p-4 md:grid-cols-[120px_1fr_2fr_auto]"><Field label="Number" value={item.number} onChange={v=>update(i,{number:v})}/><Field label="Title" value={item.title} dir={dir} onChange={v=>update(i,{title:v})}/><Field label="Text" value={item.text} dir={dir} onChange={v=>update(i,{text:v})}/><button className="self-end rounded-2xl bg-red-50 px-4 py-3 text-sm font-black text-red-700" onClick={()=>onChange(items.filter((_,n)=>n!==i))}>Remove</button></div>)}</div>;
}

export default function AdminProjectsPage(){
  const [locale,setLocale]=useState<Locale>("ar"); const [content,setContent]=useState<ProjectsContent>(empty); const [status,setStatus]=useState("Loading…"); const [busy,setBusy]=useState(true); const dir=locale==="ar"?"rtl":"ltr";
  const load=useCallback(async()=>{setBusy(true);setStatus("Loading…");try{const r=await adminFetch(`/api/admin/projects?locale=${locale}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message||"Load failed");setContent(d.content);setStatus("Loaded");}catch(e){setStatus(e instanceof Error?e.message:"Load failed");}finally{setBusy(false)}},[locale]);
  useEffect(()=>{void load()},[load]);
  async function save(){setBusy(true);setStatus("Saving…");try{const r=await adminFetch(`/api/admin/projects?locale=${locale}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(content)});const d=await r.json();if(!r.ok)throw new Error(d.message||"Save failed");setContent(d.content);setStatus("Saved. The Projects page will use this content immediately.");}catch(e){setStatus(e instanceof Error?e.message:"Save failed");}finally{setBusy(false)}}
  const setField = <K extends keyof ProjectsContent>(key: K, value: ProjectsContent[K]) => setContent((current) => ({ ...current, [key]: value }));
  return <div className="mx-auto max-w-6xl space-y-6 pb-16">
    <section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-black">Projects Page</h1><p className="mt-2 text-slate-500">Edit the English and Arabic Projects page content. Colors and typography come from Theme & Style automatically.</p></div><div className="flex gap-2"><button disabled={busy} onClick={load} className="rounded-2xl border border-slate-200 px-5 py-3 font-black disabled:opacity-50">Reload</button><button disabled={busy} onClick={save} className="rounded-2xl bg-emerald-600 px-5 py-3 font-black text-white disabled:opacity-50">Save Projects</button></div></div><p className="mt-4 text-sm font-bold text-slate-500">{status}</p></section>
    <div className="flex w-fit gap-2 rounded-3xl border bg-white p-3 shadow-sm">{(["ar","en"] as Locale[]).map(x=><button key={x} onClick={()=>setLocale(x)} className={`rounded-2xl px-5 py-3 text-sm font-black ${locale===x?"bg-slate-950 text-white":"text-slate-600"}`}>{x==="ar"?"العربية":"English"}</button>)}</div>
    <Panel eyebrow="Hero" title="Projects page opening"><div className="grid gap-4 xl:grid-cols-2"><Field label="Eyebrow" value={content.eyebrow} dir={dir} onChange={v=>setField("eyebrow",v)}/><Field label="Title first line" value={content.titleA} dir={dir} onChange={v=>setField("titleA",v)}/><Field label="Title highlighted line" value={content.titleB} dir={dir} onChange={v=>setField("titleB",v)}/><Field label="Intro" value={content.intro} dir={dir} multiline onChange={v=>setField("intro",v)}/><Field label="Primary CTA" value={content.primary} dir={dir} onChange={v=>setField("primary",v)}/><Field label="Secondary CTA" value={content.secondary} dir={dir} onChange={v=>setField("secondary",v)}/></div></Panel>
    <Panel eyebrow="Websites & CMS" title="Website and CMS section"><div className="mb-6 grid gap-4 xl:grid-cols-2"><Field label="Kicker" value={content.digitalKicker} dir={dir} onChange={v=>setField("digitalKicker",v)}/><Field label="Title" value={content.digitalTitle} dir={dir} onChange={v=>setField("digitalTitle",v)}/><div className="xl:col-span-2"><Field label="Description" value={content.digitalText} dir={dir} multiline onChange={v=>setField("digitalText",v)}/></div></div><ProjectEditor title="Website & CMS projects" items={content.digitalProjects} onChange={v=>setField("digitalProjects",v)} dir={dir}/></Panel>
    <Panel eyebrow="Operating Solutions" title="Operating solutions section"><div className="mb-6 grid gap-4 xl:grid-cols-2"><Field label="Kicker" value={content.opsKicker} dir={dir} onChange={v=>setField("opsKicker",v)}/><Field label="Title" value={content.opsTitle} dir={dir} onChange={v=>setField("opsTitle",v)}/><div className="xl:col-span-2"><Field label="Description" value={content.opsText} dir={dir} multiline onChange={v=>setField("opsText",v)}/></div></div><ProjectEditor title="Operating solution projects" items={content.operatingProjects} onChange={v=>setField("operatingProjects",v)} dir={dir}/></Panel>
    <Panel eyebrow="Outcomes" title="Value / outcome section"><div className="mb-6 grid gap-4 xl:grid-cols-2"><Field label="Kicker" value={content.outcomeKicker} dir={dir} onChange={v=>setField("outcomeKicker",v)}/><Field label="Title" value={content.outcomeTitle} dir={dir} onChange={v=>setField("outcomeTitle",v)}/></div><OutcomeEditor items={content.outcomes} onChange={v=>setField("outcomes",v)} dir={dir}/></Panel>
    <Panel eyebrow="CTA" title="Final project call to action"><div className="grid gap-4 xl:grid-cols-2"><Field label="Title" value={content.ctaTitle} dir={dir} onChange={v=>setField("ctaTitle",v)}/><Field label="Button" value={content.cta} dir={dir} onChange={v=>setField("cta",v)}/><div className="xl:col-span-2"><Field label="Text" value={content.ctaText} dir={dir} multiline onChange={v=>setField("ctaText",v)}/></div><Field label="CMS visual label" value={content.cmsLabel} onChange={v=>setField("cmsLabel",v)}/><Field label="Website visual label" value={content.liveLabel} onChange={v=>setField("liveLabel",v)}/><Field label="Operations visual label" value={content.workflowLabel} onChange={v=>setField("workflowLabel",v)}/></div></Panel>
  </div>;
}
